spring.application.name=SpringBootBasics
spring.datasource.url=jdbc:postgresql://localhost:5432/codepilot
spring.datasource.username=postgres
spring.datasource.password=8801957245

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true